<a href="https://colab.research.google.com/github/MeghanGH/google-colaboratory/blob/main/Exploratory_Data_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

### Import Google Sheet

In [ ]:
from google.colab import auth
auth.authenticate_user()

import gspread
from google.auth import default
creds, _ = default()

gc = gspread.authorize(creds)

In [ ]:
worksheet = gc.open('state').sheet1

# get_all_values gives a list of rows.
rows = worksheet.get_all_values()
print(rows)

import pandas as pd
pd.DataFrame.from_records(rows)

[['State', 'Population', 'Murder.Rate', 'Abbreviation'], ['Alabama', '4779736', '5.7', 'AL'], ['Alaska', '710231', '5.6', 'AK'], ['Arizona', '6392017', '4.7', 'AZ'], ['Arkansas', '2915918', '5.6', 'AR'], ['California', '37253956', '4.4', 'CA'], ['Colorado', '5029196', '2.8', 'CO'], ['Connecticut', '3574097', '2.4', 'CT'], ['Delaware', '897934', '5.8', 'DE'], ['Florida', '18801310', '5.8', 'FL'], ['Georgia', '9687653', '5.7', 'GA'], ['Hawaii', '1360301', '1.8', 'HI'], ['Idaho', '1567582', '2', 'ID'], ['Illinois', '12830632', '5.3', 'IL'], ['Indiana', '6483802', '5', 'IN'], ['Iowa', '3046355', '1.9', 'IA'], ['Kansas', '2853118', '3.1', 'KS'], ['Kentucky', '4339367', '3.6', 'KY'], ['Louisiana', '4533372', '10.3', 'LA'], ['Maine', '1328361', '1.6', 'ME'], ['Maryland', '5773552', '6.1', 'MD'], ['Massachusetts', '6547629', '2', 'MA'], ['Michigan', '9883640', '5.4', 'MI'], ['Minnesota', '5303925', '1.6', 'MN'], ['Mississippi', '2967297', '8.6', 'MS'], ['Missouri', '5988927', '6.6', 'MO'], ['Montana', '989415', '3.6', 'MT'], ['Nebraska', '1826341', '2.9', 'NE'], ['Nevada', '2700551', '6', 'NV'], ['New Hampshire', '1316470', '0.9', 'NH'], ['New Jersey', '8791894', '3.9', 'NJ'], ['New Mexico', '2059179', '4.8', 'NM'], ['New York', '19378102', '3.1', 'NY'], ['North Carolina', '9535483', '5.1', 'NC'], ['North Dakota', '672591', '3', 'ND'], ['Ohio', '11536504', '4', 'OH'], ['Oklahoma', '3751351', '4.5', 'OK'], ['Oregon', '3831074', '2', 'OR'], ['Pennsylvania', '12702379', '4.8', 'PA'], ['Rhode Island', '1052567', '2.4', 'RI'], ['South Carolina', '4625364', '6.4', 'SC'], ['South Dakota', '814180', '2.3', 'SD'], ['Tennessee', '6346105', '5.7', 'TN'], ['Texas', '25145561', '4.4', 'TX'], ['Utah', '2763885', '2.3', 'UT'], ['Vermont', '625741', '1.6', 'VT'], ['Virginia', '8001024', '4.1', 'VA'], ['Washington', '6724540', '2.5', 'WA'], ['West Virginia', '1852994', '4', 'WV'], ['Wisconsin', '5686986', '2.9', 'WI'], ['Wyoming', '563626', '2.7', 'WY']]

                 0           1            2             3
0            State  Population  Murder.Rate  Abbreviation
1          Alabama     4779736          5.7            AL
2           Alaska      710231          5.6            AK
3          Arizona     6392017          4.7            AZ
4         Arkansas     2915918          5.6            AR
5       California    37253956          4.4            CA
6         Colorado     5029196          2.8            CO
7      Connecticut     3574097          2.4            CT
8         Delaware      897934          5.8            DE
9          Florida    18801310          5.8            FL
10         Georgia     9687653          5.7            GA
11          Hawaii     1360301          1.8            HI
12           Idaho     1567582            2            ID
13        Illinois    12830632          5.3            IL
14         Indiana     6483802            5            IN
15            Iowa     3046355          1.9            IA
16          Kansas     2853118          3.1            KS
17        Kentucky     4339367          3.6            KY
18       Louisiana     4533372         10.3            LA
19           Maine     1328361          1.6            ME
20        Maryland     5773552          6.1            MD
21   Massachusetts     6547629            2            MA
22        Michigan     9883640          5.4            MI
23       Minnesota     5303925          1.6            MN
24     Mississippi     2967297          8.6            MS
25        Missouri     5988927          6.6            MO
26         Montana      989415          3.6            MT
27        Nebraska     1826341          2.9            NE
28          Nevada     2700551            6            NV
29   New Hampshire     1316470          0.9            NH
30      New Jersey     8791894          3.9            NJ
31      New Mexico     2059179          4.8            NM
32        New York    19378102          3.1            NY
33  North Carolina     9535483          5.1            NC
34    North Dakota      672591            3            ND
35            Ohio    11536504            4            OH
36        Oklahoma     3751351          4.5            OK
37          Oregon     3831074            2            OR
38    Pennsylvania    12702379          4.8            PA
39    Rhode Island     1052567          2.4            RI
40  South Carolina     4625364          6.4            SC
41    South Dakota      814180          2.3            SD
42       Tennessee     6346105          5.7            TN
43           Texas    25145561          4.4            TX
44            Utah     2763885          2.3            UT
45         Vermont      625741          1.6            VT
46        Virginia     8001024          4.1            VA
47      Washington     6724540          2.5            WA
48   West Virginia     1852994            4            WV
49       Wisconsin     5686986          2.9            WI
50         Wyoming      563626          2.7            WY

## Import local file

In [ ]:
import pandas as pd

state = '/content/drive/MyDrive/ColabNotebooks/data/state.csv'

df_state = pd.read_csv(state)
print(df_state)

             State  Population  Murder.Rate Abbreviation
0          Alabama     4779736          5.7           AL
1           Alaska      710231          5.6           AK
2          Arizona     6392017          4.7           AZ
3         Arkansas     2915918          5.6           AR
4       California    37253956          4.4           CA
5         Colorado     5029196          2.8           CO
6      Connecticut     3574097          2.4           CT
7         Delaware      897934          5.8           DE
8          Florida    18801310          5.8           FL
9          Georgia     9687653          5.7           GA
10          Hawaii     1360301          1.8           HI
11           Idaho     1567582          2.0           ID
12        Illinois    12830632          5.3           IL
13         Indiana     6483802          5.0           IN
14            Iowa     3046355          1.9           IA
15          Kansas     2853118          3.1           KS
16        Kentucky     4339367          3.6           KY
17       Louisiana     4533372         10.3           LA
18           Maine     1328361          1.6           ME
19        Maryland     5773552          6.1           MD
20   Massachusetts     6547629          2.0           MA
21        Michigan     9883640          5.4           MI
22       Minnesota     5303925          1.6           MN
23     Mississippi     2967297          8.6           MS
24        Missouri     5988927          6.6           MO
25         Montana      989415          3.6           MT
26        Nebraska     1826341          2.9           NE
27          Nevada     2700551          6.0           NV
28   New Hampshire     1316470          0.9           NH
29      New Jersey     8791894          3.9           NJ
30      New Mexico     2059179          4.8           NM
31        New York    19378102          3.1           NY
32  North Carolina     9535483          5.1           NC
33    North Dakota      672591          3.0           ND
34            Ohio    11536504          4.0           OH
35        Oklahoma     3751351          4.5           OK
36          Oregon     3831074          2.0           OR
37    Pennsylvania    12702379          4.8           PA
38    Rhode Island     1052567          2.4           RI
39  South Carolina     4625364          6.4           SC
40    South Dakota      814180          2.3           SD
41       Tennessee     6346105          5.7           TN
42           Texas    25145561          4.4           TX
43            Utah     2763885          2.3           UT
44         Vermont      625741          1.6           VT
45        Virginia     8001024          4.1           VA
46      Washington     6724540          2.5           WA
47   West Virginia     1852994          4.0           WV
48       Wisconsin     5686986          2.9           WI
49         Wyoming      563626          2.7           WY

Using local file

In [ ]:
df_state['Population'].mean()

6162876.3

In [ ]:
df_state['Population'].median()

4436369.5